env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:react/jsx-runtime
    - plugin:@typescript-eslint/recommended
    - prettier
parser: "@typescript-eslint/parser"
settings:
    react:
        version: "detect"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
ignorePatterns:
    - "updates/*.js"
rules:
    quotes:
        - error
        - double
        - avoidEscape: true
          allowTemplateLiterals: false
    no-duplicate-imports: error
    no-unreachable: error
    camelcase: off
    eqeqeq: error
    no-eval: error
    no-invalid-this: error
    no-shadow: error
    no-var: error
    prefer-const: error
    prefer-template: error
    spaced-comment: warn
    yoda: warn
    no-new-symbol: off
    symbol-description: off
    "@typescript-eslint/no-non-null-assertion": off
