on:
    release:
        types: [released]

jobs:
    UpdateVersionFile:
        name: "Update Version File"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3.3.0
            - name: Update File
              run: |
                  cd updates
                  node generateUpdateFile.js
                  cd ..
            - name: Commit Changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add updates/latest-version.json
                  git commit -m "Updated Version File"
            - name: Push Schemas
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.github_token }}
                  branch: ${{ github.ref }}
