name: Publish Release

on:
    workflow_dispatch:
    release:
        types: [released, edited]

jobs:
    UpdateVersionFile:
        name: "Update Version File"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: main

            - name: Setup Node
              uses: actions/setup-node@v3.3.0

            # Don't @ me
            - name: Get Signatures
              run: |
                  cd updates
                  wget https://github.com/Outer-Wilds-New-Horizons/nh-config-editor/releases/download/${{ github.event.release.tag_name }}/New.Horizons.Config.Editor_${{ github.event.release.tag_name }}_x64_en-US.msi.zip.sig
                  wget https://github.com/Outer-Wilds-New-Horizons/nh-config-editor/releases/download/${{ github.event.release.tag_name }}/new-horizons-config-editor_${{ github.event.release.tag_name }}_amd64.AppImage.tar.gz.sig
                  wget https://github.com/Outer-Wilds-New-Horizons/nh-config-editor/releases/download/${{ github.event.release.tag_name }}/New.Horizons.Config.Editor.app.tar.gz.sig
                  cd ..

            - name: Install pnpm
              uses: pnpm/action-setup@v2.0.1
              id: pnpm-install
              with:
                  version: 6.11.0
                  run_install: false

            - name: Install pnpm Dependencies
              run: pnpm install

            - name: Update File
              run: |
                  cd updates
                  node generateUpdateFile.js
                  cd ..

            - name: Commit Changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add updates/latest-version.json
                  git commit -m "Updated Version File"

            - name: Push Schemas
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.github_token }}
                  branch: main
